# Generated by Django 4.1.3 on 2022-11-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avaliable',
            field=models.BooleanField(default=True),
        ),
    ]
